//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;
using System.Net.Security;

namespace Client.Service {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hazard.mfcr.cz/rovo/v1")]
    public partial class ErrorMessageType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int kodField;
        
        private string popisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
                this.RaisePropertyChanged("Kod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Popis {
            get {
                return this.popisField;
            }
            set {
                this.popisField = value;
                this.RaisePropertyChanged("Popis");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hazard.mfcr.cz/rovo/v1")]
    public partial class BaseResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cisloPozadavkuField;
        
        private string identifikacePozadavkuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CisloPozadavku {
            get {
                return this.cisloPozadavkuField;
            }
            set {
                this.cisloPozadavkuField = value;
                this.RaisePropertyChanged("CisloPozadavku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IdentifikacePozadavku {
            get {
                return this.identifikacePozadavkuField;
            }
            set {
                this.identifikacePozadavkuField = value;
                this.RaisePropertyChanged("IdentifikacePozadavku");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hazard.mfcr.cz/rovo/v1")]
    public partial class TrvalyPobytSvetType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uliceField;
        
        private string cisloPopisneEvidencniField;
        
        private string cisloOrientacniField;
        
        private string cisloOrientacniDodatekField;
        
        private string obecCastField;
        
        private string obecField;
        
        private string pSCField;
        
        private string statField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Ulice {
            get {
                return this.uliceField;
            }
            set {
                this.uliceField = value;
                this.RaisePropertyChanged("Ulice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=1)]
        public string CisloPopisneEvidencni {
            get {
                return this.cisloPopisneEvidencniField;
            }
            set {
                this.cisloPopisneEvidencniField = value;
                this.RaisePropertyChanged("CisloPopisneEvidencni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=2)]
        public string CisloOrientacni {
            get {
                return this.cisloOrientacniField;
            }
            set {
                this.cisloOrientacniField = value;
                this.RaisePropertyChanged("CisloOrientacni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CisloOrientacniDodatek {
            get {
                return this.cisloOrientacniDodatekField;
            }
            set {
                this.cisloOrientacniDodatekField = value;
                this.RaisePropertyChanged("CisloOrientacniDodatek");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ObecCast {
            get {
                return this.obecCastField;
            }
            set {
                this.obecCastField = value;
                this.RaisePropertyChanged("ObecCast");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Obec {
            get {
                return this.obecField;
            }
            set {
                this.obecField = value;
                this.RaisePropertyChanged("Obec");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PSC {
            get {
                return this.pSCField;
            }
            set {
                this.pSCField = value;
                this.RaisePropertyChanged("PSC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Stat {
            get {
                return this.statField;
            }
            set {
                this.statField = value;
                this.RaisePropertyChanged("Stat");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hazard.mfcr.cz/rovo/v1")]
    public partial class TrvalyPobytCRType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uliceField;
        
        private string cisloPopisneEvidencniField;
        
        private string cisloOrientacniField;
        
        private string cisloOrientacniDodatekField;
        
        private string cisloObvodMestaPrahyField;
        
        private string obecCastField;
        
        private string obecField;
        
        private int pSCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Ulice {
            get {
                return this.uliceField;
            }
            set {
                this.uliceField = value;
                this.RaisePropertyChanged("Ulice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=1)]
        public string CisloPopisneEvidencni {
            get {
                return this.cisloPopisneEvidencniField;
            }
            set {
                this.cisloPopisneEvidencniField = value;
                this.RaisePropertyChanged("CisloPopisneEvidencni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=2)]
        public string CisloOrientacni {
            get {
                return this.cisloOrientacniField;
            }
            set {
                this.cisloOrientacniField = value;
                this.RaisePropertyChanged("CisloOrientacni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CisloOrientacniDodatek {
            get {
                return this.cisloOrientacniDodatekField;
            }
            set {
                this.cisloOrientacniDodatekField = value;
                this.RaisePropertyChanged("CisloOrientacniDodatek");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=4)]
        public string CisloObvodMestaPrahy {
            get {
                return this.cisloObvodMestaPrahyField;
            }
            set {
                this.cisloObvodMestaPrahyField = value;
                this.RaisePropertyChanged("CisloObvodMestaPrahy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ObecCast {
            get {
                return this.obecCastField;
            }
            set {
                this.obecCastField = value;
                this.RaisePropertyChanged("ObecCast");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Obec {
            get {
                return this.obecField;
            }
            set {
                this.obecField = value;
                this.RaisePropertyChanged("Obec");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int PSC {
            get {
                return this.pSCField;
            }
            set {
                this.pSCField = value;
                this.RaisePropertyChanged("PSC");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hazard.mfcr.cz/rovo/v1")]
    public partial class TrvalyPobytType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int trvalyPobytKodField;
        
        private bool trvalyPobytKodFieldSpecified;
        
        private TrvalyPobytCRType trvalyPobytCRField;
        
        private TrvalyPobytSvetType trvalyPobytSvetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TrvalyPobytKod {
            get {
                return this.trvalyPobytKodField;
            }
            set {
                this.trvalyPobytKodField = value;
                this.RaisePropertyChanged("TrvalyPobytKod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TrvalyPobytKodSpecified {
            get {
                return this.trvalyPobytKodFieldSpecified;
            }
            set {
                this.trvalyPobytKodFieldSpecified = value;
                this.RaisePropertyChanged("TrvalyPobytKodSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TrvalyPobytCRType TrvalyPobytCR {
            get {
                return this.trvalyPobytCRField;
            }
            set {
                this.trvalyPobytCRField = value;
                this.RaisePropertyChanged("TrvalyPobytCR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TrvalyPobytSvetType TrvalyPobytSvet {
            get {
                return this.trvalyPobytSvetField;
            }
            set {
                this.trvalyPobytSvetField = value;
                this.RaisePropertyChanged("TrvalyPobytSvet");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hazard.mfcr.cz/rovo/v1")]
    public partial class MistoNarozeniSvetType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mistoField;
        
        private string statField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Misto {
            get {
                return this.mistoField;
            }
            set {
                this.mistoField = value;
                this.RaisePropertyChanged("Misto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Stat {
            get {
                return this.statField;
            }
            set {
                this.statField = value;
                this.RaisePropertyChanged("Stat");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hazard.mfcr.cz/rovo/v1")]
    public partial class MistoNarozeniCRType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string obecField;
        
        private string okresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Obec {
            get {
                return this.obecField;
            }
            set {
                this.obecField = value;
                this.RaisePropertyChanged("Obec");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Okres {
            get {
                return this.okresField;
            }
            set {
                this.okresField = value;
                this.RaisePropertyChanged("Okres");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hazard.mfcr.cz/rovo/v1")]
    public partial class MistoNarozeniType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int mistoNarozeniKodField;
        
        private bool mistoNarozeniKodFieldSpecified;
        
        private MistoNarozeniCRType mistoNarozeniCRField;
        
        private MistoNarozeniSvetType mistoNarozeniSvetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int MistoNarozeniKod {
            get {
                return this.mistoNarozeniKodField;
            }
            set {
                this.mistoNarozeniKodField = value;
                this.RaisePropertyChanged("MistoNarozeniKod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MistoNarozeniKodSpecified {
            get {
                return this.mistoNarozeniKodFieldSpecified;
            }
            set {
                this.mistoNarozeniKodFieldSpecified = value;
                this.RaisePropertyChanged("MistoNarozeniKodSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MistoNarozeniCRType MistoNarozeniCR {
            get {
                return this.mistoNarozeniCRField;
            }
            set {
                this.mistoNarozeniCRField = value;
                this.RaisePropertyChanged("MistoNarozeniCR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public MistoNarozeniSvetType MistoNarozeniSvet {
            get {
                return this.mistoNarozeniSvetField;
            }
            set {
                this.mistoNarozeniSvetField = value;
                this.RaisePropertyChanged("MistoNarozeniSvet");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hazard.mfcr.cz/rovo/v1")]
    public partial class OsobaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string jmenoField;
        
        private string prijmeniField;
        
        private string rodnePrijmeniField;
        
        private System.DateTime datumNarozeniField;
        
        private string statniObcanstviField;
        
        private MistoNarozeniType mistoNarozeniField;
        
        private TrvalyPobytType trvalyPobytField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Jmeno {
            get {
                return this.jmenoField;
            }
            set {
                this.jmenoField = value;
                this.RaisePropertyChanged("Jmeno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Prijmeni {
            get {
                return this.prijmeniField;
            }
            set {
                this.prijmeniField = value;
                this.RaisePropertyChanged("Prijmeni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RodnePrijmeni {
            get {
                return this.rodnePrijmeniField;
            }
            set {
                this.rodnePrijmeniField = value;
                this.RaisePropertyChanged("RodnePrijmeni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime DatumNarozeni {
            get {
                return this.datumNarozeniField;
            }
            set {
                this.datumNarozeniField = value;
                this.RaisePropertyChanged("DatumNarozeni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string StatniObcanstvi {
            get {
                return this.statniObcanstviField;
            }
            set {
                this.statniObcanstviField = value;
                this.RaisePropertyChanged("StatniObcanstvi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public MistoNarozeniType MistoNarozeni {
            get {
                return this.mistoNarozeniField;
            }
            set {
                this.mistoNarozeniField = value;
                this.RaisePropertyChanged("MistoNarozeni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public TrvalyPobytType TrvalyPobyt {
            get {
                return this.trvalyPobytField;
            }
            set {
                this.trvalyPobytField = value;
                this.RaisePropertyChanged("TrvalyPobyt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hazard.mfcr.cz/rovo/v1")]
    public partial class BaseRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cisloPozadavkuField;
        
        private string iCO_VCPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CisloPozadavku {
            get {
                return this.cisloPozadavkuField;
            }
            set {
                this.cisloPozadavkuField = value;
                this.RaisePropertyChanged("CisloPozadavku");
            }
        }

        /// <remarks/>
        [JsonProperty(PropertyName = "icovcp")]
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ICO_VCP {
            get {
                return this.iCO_VCPField;
            }
            set {
                this.iCO_VCPField = value;
                this.RaisePropertyChanged("ICO_VCP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://hazard.mfcr.cz/rovo/v1", ConfigurationName="Service.AisgPort", ProtectionLevel=ProtectionLevel.Sign)]
    public interface AisgPort {
        
        // CODEGEN: Generating message contract since the operation ZmenitUdajeOsoby is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="ZmenitUdajeOsoby", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Client.Service.ErrorMessageType), Action="ZmenitUdajeOsoby", Name="ErrorMessage")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequestType))]
        Client.Service.ZmenitUdajeOsobyResponse ZmenitUdajeOsoby(Client.Service.ZmenitUdajeOsoby request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ZmenitUdajeOsoby", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.Service.ZmenitUdajeOsobyResponse> ZmenitUdajeOsobyAsync(Client.Service.ZmenitUdajeOsoby request);
        
        // CODEGEN: Generating message contract since the operation OveritOsobyHromadne is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="OveritOsobyHromadne", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Client.Service.ErrorMessageType), Action="OveritOsobyHromadne", Name="ErrorMessage")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequestType))]
        Client.Service.OveritOsobyHromadneResponse1 OveritOsobyHromadne(Client.Service.OveritOsobyHromadne request);
        
        [System.ServiceModel.OperationContractAttribute(Action="OveritOsobyHromadne", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.Service.OveritOsobyHromadneResponse1> OveritOsobyHromadneAsync(Client.Service.OveritOsobyHromadne request);
        
        // CODEGEN: Generating message contract since the operation ZiskatVysledkyOveritOsobyHromadne is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="ZiskatVysledkyOveritOsobyHromadne", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Client.Service.ErrorMessageType), Action="ZiskatVysledkyOveritOsobyHromadne", Name="ErrorMessage")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequestType))]
        Client.Service.ZiskatVysledkyOveritOsobyHromadneResponse1 ZiskatVysledkyOveritOsobyHromadne(Client.Service.ZiskatVysledkyOveritOsobyHromadne request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ZiskatVysledkyOveritOsobyHromadne", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.Service.ZiskatVysledkyOveritOsobyHromadneResponse1> ZiskatVysledkyOveritOsobyHromadneAsync(Client.Service.ZiskatVysledkyOveritOsobyHromadne request);
        
        // CODEGEN: Generating message contract since the operation OveritOsobu is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="OveritOsobu", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Client.Service.ErrorMessageType), Action="OveritOsobu", Name="ErrorMessage")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequestType))]
        Client.Service.OveritOsobuResponse1 OveritOsobu(Client.Service.OveritOsobu request);
        
        [System.ServiceModel.OperationContractAttribute(Action="OveritOsobu", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.Service.OveritOsobuResponse1> OveritOsobuAsync(Client.Service.OveritOsobu request);
        
        // CODEGEN: Generating message contract since the operation Test is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="Test", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Client.Service.ErrorMessageType), Action="Test", Name="ErrorMessage")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequestType))]
        Client.Service.TestResponse Test(Client.Service.Test request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Test", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.Service.TestResponse> TestAsync(Client.Service.Test request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hazard.mfcr.cz/rovo/v1")]
    public partial class ZmenitUdajeOsobyRequest : BaseRequestType {
        
        private string hIDField;
        
        private OsobaType osobaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string HID {
            get {
                return this.hIDField;
            }
            set {
                this.hIDField = value;
                this.RaisePropertyChanged("HID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OsobaType Osoba {
            get {
                return this.osobaField;
            }
            set {
                this.osobaField = value;
                this.RaisePropertyChanged("Osoba");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZmenitUdajeOsoby {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hazard.mfcr.cz/rovo/v1", Order=0)]
        public Client.Service.ZmenitUdajeOsobyRequest ZmenitUdajeOsobyRequest;
        
        public ZmenitUdajeOsoby() {
        }
        
        public ZmenitUdajeOsoby(Client.Service.ZmenitUdajeOsobyRequest ZmenitUdajeOsobyRequest) {
            this.ZmenitUdajeOsobyRequest = ZmenitUdajeOsobyRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZmenitUdajeOsobyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZmenitUdajeOsobyResponse", Namespace="http://hazard.mfcr.cz/rovo/v1", Order=0)]
        public Client.Service.BaseResponseType ZmenitUdajeOsobyResponse1;
        
        public ZmenitUdajeOsobyResponse() {
        }
        
        public ZmenitUdajeOsobyResponse(Client.Service.BaseResponseType ZmenitUdajeOsobyResponse1) {
            this.ZmenitUdajeOsobyResponse1 = ZmenitUdajeOsobyResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hazard.mfcr.cz/rovo/v1")]
    public partial class OveritOsobyHromadneRequest : BaseRequestType {
        
        private OsobaKOvereniType[] osobyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("OsobaKOvereni", IsNullable=false)]
        public OsobaKOvereniType[] Osoby {
            get {
                return this.osobyField;
            }
            set {
                this.osobyField = value;
                this.RaisePropertyChanged("Osoby");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hazard.mfcr.cz/rovo/v1")]
    public partial class OsobaKOvereniType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string identifikaceZaznamuField;
        
        private OsobaType osobaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdentifikaceZaznamu {
            get {
                return this.identifikaceZaznamuField;
            }
            set {
                this.identifikaceZaznamuField = value;
                this.RaisePropertyChanged("IdentifikaceZaznamu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OsobaType Osoba {
            get {
                return this.osobaField;
            }
            set {
                this.osobaField = value;
                this.RaisePropertyChanged("Osoba");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hazard.mfcr.cz/rovo/v1")]
    public partial class OveritOsobyHromadneResponse : BaseResponseType {
        
        private string cisloDavkyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CisloDavky {
            get {
                return this.cisloDavkyField;
            }
            set {
                this.cisloDavkyField = value;
                this.RaisePropertyChanged("CisloDavky");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OveritOsobyHromadne {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hazard.mfcr.cz/rovo/v1", Order=0)]
        public Client.Service.OveritOsobyHromadneRequest OveritOsobyHromadneRequest;
        
        public OveritOsobyHromadne() {
        }
        
        public OveritOsobyHromadne(Client.Service.OveritOsobyHromadneRequest OveritOsobyHromadneRequest) {
            this.OveritOsobyHromadneRequest = OveritOsobyHromadneRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OveritOsobyHromadneResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hazard.mfcr.cz/rovo/v1", Order=0)]
        public Client.Service.OveritOsobyHromadneResponse OveritOsobyHromadneResponse;
        
        public OveritOsobyHromadneResponse1() {
        }
        
        public OveritOsobyHromadneResponse1(Client.Service.OveritOsobyHromadneResponse OveritOsobyHromadneResponse) {
            this.OveritOsobyHromadneResponse = OveritOsobyHromadneResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hazard.mfcr.cz/rovo/v1")]
    public partial class ZiskatVysledkyOveritOsobyHromadneRequest : BaseRequestType {
        
        private string cisloDavkyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CisloDavky {
            get {
                return this.cisloDavkyField;
            }
            set {
                this.cisloDavkyField = value;
                this.RaisePropertyChanged("CisloDavky");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hazard.mfcr.cz/rovo/v1")]
    public partial class ZiskatVysledkyOveritOsobyHromadneResponse : BaseResponseType {
        
        private string stavField;
        
        private OsobaKOvereniVysledekTypeOsobaKOvereniVysledek[] osobyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Stav {
            get {
                return this.stavField;
            }
            set {
                this.stavField = value;
                this.RaisePropertyChanged("Stav");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("OsobaKOvereniVysledek", IsNullable=false)]
        public OsobaKOvereniVysledekTypeOsobaKOvereniVysledek[] Osoby {
            get {
                return this.osobyField;
            }
            set {
                this.osobyField = value;
                this.RaisePropertyChanged("Osoby");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hazard.mfcr.cz/rovo/v1")]
    public partial class OsobaKOvereniVysledekTypeOsobaKOvereniVysledek : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string identifikaceZaznamuField;
        
        private string hIDField;
        
        private string plnoletaField;
        
        private string nalezenaROBField;
        
        private string nalezenaRVOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdentifikaceZaznamu {
            get {
                return this.identifikaceZaznamuField;
            }
            set {
                this.identifikaceZaznamuField = value;
                this.RaisePropertyChanged("IdentifikaceZaznamu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string HID {
            get {
                return this.hIDField;
            }
            set {
                this.hIDField = value;
                this.RaisePropertyChanged("HID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Plnoleta {
            get {
                return this.plnoletaField;
            }
            set {
                this.plnoletaField = value;
                this.RaisePropertyChanged("Plnoleta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NalezenaROB {
            get {
                return this.nalezenaROBField;
            }
            set {
                this.nalezenaROBField = value;
                this.RaisePropertyChanged("NalezenaROB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NalezenaRVO {
            get {
                return this.nalezenaRVOField;
            }
            set {
                this.nalezenaRVOField = value;
                this.RaisePropertyChanged("NalezenaRVO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZiskatVysledkyOveritOsobyHromadne {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hazard.mfcr.cz/rovo/v1", Order=0)]
        public Client.Service.ZiskatVysledkyOveritOsobyHromadneRequest ZiskatVysledkyOveritOsobyHromadneRequest;
        
        public ZiskatVysledkyOveritOsobyHromadne() {
        }
        
        public ZiskatVysledkyOveritOsobyHromadne(Client.Service.ZiskatVysledkyOveritOsobyHromadneRequest ZiskatVysledkyOveritOsobyHromadneRequest) {
            this.ZiskatVysledkyOveritOsobyHromadneRequest = ZiskatVysledkyOveritOsobyHromadneRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZiskatVysledkyOveritOsobyHromadneResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hazard.mfcr.cz/rovo/v1", Order=0)]
        public Client.Service.ZiskatVysledkyOveritOsobyHromadneResponse ZiskatVysledkyOveritOsobyHromadneResponse;
        
        public ZiskatVysledkyOveritOsobyHromadneResponse1() {
        }
        
        public ZiskatVysledkyOveritOsobyHromadneResponse1(Client.Service.ZiskatVysledkyOveritOsobyHromadneResponse ZiskatVysledkyOveritOsobyHromadneResponse) {
            this.ZiskatVysledkyOveritOsobyHromadneResponse = ZiskatVysledkyOveritOsobyHromadneResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hazard.mfcr.cz/rovo/v1")]
    public partial class OveritOsobuRequest : BaseRequestType {
        
        private string duvodField;
        
        private string hIDField;
        
        private OsobaType osobaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Duvod {
            get {
                return this.duvodField;
            }
            set {
                this.duvodField = value;
                this.RaisePropertyChanged("Duvod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string HID {
            get {
                return this.hIDField;
            }
            set {
                this.hIDField = value;
                this.RaisePropertyChanged("HID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public OsobaType Osoba {
            get {
                return this.osobaField;
            }
            set {
                this.osobaField = value;
                this.RaisePropertyChanged("Osoba");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://hazard.mfcr.cz/rovo/v1")]
    public partial class OveritOsobuResponse : BaseResponseType {
        
        private string hIDField;
        
        private string plnoletaField;
        
        private string nalezenaROBField;
        
        private string nalezenaRVOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string HID {
            get {
                return this.hIDField;
            }
            set {
                this.hIDField = value;
                this.RaisePropertyChanged("HID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Plnoleta {
            get {
                return this.plnoletaField;
            }
            set {
                this.plnoletaField = value;
                this.RaisePropertyChanged("Plnoleta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NalezenaROB {
            get {
                return this.nalezenaROBField;
            }
            set {
                this.nalezenaROBField = value;
                this.RaisePropertyChanged("NalezenaROB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NalezenaRVO {
            get {
                return this.nalezenaRVOField;
            }
            set {
                this.nalezenaRVOField = value;
                this.RaisePropertyChanged("NalezenaRVO");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OveritOsobu {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hazard.mfcr.cz/rovo/v1", Order=0)]
        public Client.Service.OveritOsobuRequest OveritOsobuRequest;
        
        public OveritOsobu() {
        }
        
        public OveritOsobu(Client.Service.OveritOsobuRequest OveritOsobuRequest) {
            this.OveritOsobuRequest = OveritOsobuRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OveritOsobuResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hazard.mfcr.cz/rovo/v1", Order=0)]
        public Client.Service.OveritOsobuResponse OveritOsobuResponse;
        
        public OveritOsobuResponse1() {
        }
        
        public OveritOsobuResponse1(Client.Service.OveritOsobuResponse OveritOsobuResponse) {
            this.OveritOsobuResponse = OveritOsobuResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Test {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hazard.mfcr.cz/rovo/v1", Order=0)]
        public Client.Service.BaseRequestType TestRequest;
        
        public Test() {
        }
        
        public Test(Client.Service.BaseRequestType TestRequest) {
            this.TestRequest = TestRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestResponse", Namespace="http://hazard.mfcr.cz/rovo/v1", Order=0)]
        public Client.Service.BaseResponseType TestResponse1;
        
        public TestResponse() {
        }
        
        public TestResponse(Client.Service.BaseResponseType TestResponse1) {
            this.TestResponse1 = TestResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AisgPortChannel : Client.Service.AisgPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AisgPortClient : System.ServiceModel.ClientBase<Client.Service.AisgPort>, Client.Service.AisgPort {
        
        public AisgPortClient() {
        }
        
        public AisgPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AisgPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AisgPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AisgPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.Service.ZmenitUdajeOsobyResponse Client.Service.AisgPort.ZmenitUdajeOsoby(Client.Service.ZmenitUdajeOsoby request) {
            return base.Channel.ZmenitUdajeOsoby(request);
        }
        
        public Client.Service.BaseResponseType ZmenitUdajeOsoby(Client.Service.ZmenitUdajeOsobyRequest ZmenitUdajeOsobyRequest) {
            Client.Service.ZmenitUdajeOsoby inValue = new Client.Service.ZmenitUdajeOsoby();
            inValue.ZmenitUdajeOsobyRequest = ZmenitUdajeOsobyRequest;
            Client.Service.ZmenitUdajeOsobyResponse retVal = ((Client.Service.AisgPort)(this)).ZmenitUdajeOsoby(inValue);
            return retVal.ZmenitUdajeOsobyResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Service.ZmenitUdajeOsobyResponse> Client.Service.AisgPort.ZmenitUdajeOsobyAsync(Client.Service.ZmenitUdajeOsoby request) {
            return base.Channel.ZmenitUdajeOsobyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Service.ZmenitUdajeOsobyResponse> ZmenitUdajeOsobyAsync(Client.Service.ZmenitUdajeOsobyRequest ZmenitUdajeOsobyRequest) {
            Client.Service.ZmenitUdajeOsoby inValue = new Client.Service.ZmenitUdajeOsoby();
            inValue.ZmenitUdajeOsobyRequest = ZmenitUdajeOsobyRequest;
            return ((Client.Service.AisgPort)(this)).ZmenitUdajeOsobyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.Service.OveritOsobyHromadneResponse1 Client.Service.AisgPort.OveritOsobyHromadne(Client.Service.OveritOsobyHromadne request) {
            return base.Channel.OveritOsobyHromadne(request);
        }
        
        public Client.Service.OveritOsobyHromadneResponse OveritOsobyHromadne(Client.Service.OveritOsobyHromadneRequest OveritOsobyHromadneRequest) {
            Client.Service.OveritOsobyHromadne inValue = new Client.Service.OveritOsobyHromadne();
            inValue.OveritOsobyHromadneRequest = OveritOsobyHromadneRequest;
            Client.Service.OveritOsobyHromadneResponse1 retVal = ((Client.Service.AisgPort)(this)).OveritOsobyHromadne(inValue);
            return retVal.OveritOsobyHromadneResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Service.OveritOsobyHromadneResponse1> Client.Service.AisgPort.OveritOsobyHromadneAsync(Client.Service.OveritOsobyHromadne request) {
            return base.Channel.OveritOsobyHromadneAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Service.OveritOsobyHromadneResponse1> OveritOsobyHromadneAsync(Client.Service.OveritOsobyHromadneRequest OveritOsobyHromadneRequest) {
            Client.Service.OveritOsobyHromadne inValue = new Client.Service.OveritOsobyHromadne();
            inValue.OveritOsobyHromadneRequest = OveritOsobyHromadneRequest;
            return ((Client.Service.AisgPort)(this)).OveritOsobyHromadneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.Service.ZiskatVysledkyOveritOsobyHromadneResponse1 Client.Service.AisgPort.ZiskatVysledkyOveritOsobyHromadne(Client.Service.ZiskatVysledkyOveritOsobyHromadne request) {
            return base.Channel.ZiskatVysledkyOveritOsobyHromadne(request);
        }
        
        public Client.Service.ZiskatVysledkyOveritOsobyHromadneResponse ZiskatVysledkyOveritOsobyHromadne(Client.Service.ZiskatVysledkyOveritOsobyHromadneRequest ZiskatVysledkyOveritOsobyHromadneRequest) {
            Client.Service.ZiskatVysledkyOveritOsobyHromadne inValue = new Client.Service.ZiskatVysledkyOveritOsobyHromadne();
            inValue.ZiskatVysledkyOveritOsobyHromadneRequest = ZiskatVysledkyOveritOsobyHromadneRequest;
            Client.Service.ZiskatVysledkyOveritOsobyHromadneResponse1 retVal = ((Client.Service.AisgPort)(this)).ZiskatVysledkyOveritOsobyHromadne(inValue);
            return retVal.ZiskatVysledkyOveritOsobyHromadneResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Service.ZiskatVysledkyOveritOsobyHromadneResponse1> Client.Service.AisgPort.ZiskatVysledkyOveritOsobyHromadneAsync(Client.Service.ZiskatVysledkyOveritOsobyHromadne request) {
            return base.Channel.ZiskatVysledkyOveritOsobyHromadneAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Service.ZiskatVysledkyOveritOsobyHromadneResponse1> ZiskatVysledkyOveritOsobyHromadneAsync(Client.Service.ZiskatVysledkyOveritOsobyHromadneRequest ZiskatVysledkyOveritOsobyHromadneRequest) {
            Client.Service.ZiskatVysledkyOveritOsobyHromadne inValue = new Client.Service.ZiskatVysledkyOveritOsobyHromadne();
            inValue.ZiskatVysledkyOveritOsobyHromadneRequest = ZiskatVysledkyOveritOsobyHromadneRequest;
            return ((Client.Service.AisgPort)(this)).ZiskatVysledkyOveritOsobyHromadneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.Service.OveritOsobuResponse1 Client.Service.AisgPort.OveritOsobu(Client.Service.OveritOsobu request) {
            return base.Channel.OveritOsobu(request);
        }
        
        public Client.Service.OveritOsobuResponse OveritOsobu(Client.Service.OveritOsobuRequest OveritOsobuRequest) {
            Client.Service.OveritOsobu inValue = new Client.Service.OveritOsobu();
            inValue.OveritOsobuRequest = OveritOsobuRequest;
            Client.Service.OveritOsobuResponse1 retVal = ((Client.Service.AisgPort)(this)).OveritOsobu(inValue);
            return retVal.OveritOsobuResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Service.OveritOsobuResponse1> Client.Service.AisgPort.OveritOsobuAsync(Client.Service.OveritOsobu request) {
            return base.Channel.OveritOsobuAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Service.OveritOsobuResponse1> OveritOsobuAsync(Client.Service.OveritOsobuRequest OveritOsobuRequest) {
            Client.Service.OveritOsobu inValue = new Client.Service.OveritOsobu();
            inValue.OveritOsobuRequest = OveritOsobuRequest;
            return ((Client.Service.AisgPort)(this)).OveritOsobuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.Service.TestResponse Client.Service.AisgPort.Test(Client.Service.Test request) {
            return base.Channel.Test(request);
        }
        
        public Client.Service.BaseResponseType Test(Client.Service.BaseRequestType TestRequest) {
            Client.Service.Test inValue = new Client.Service.Test();
            inValue.TestRequest = TestRequest;
            Client.Service.TestResponse retVal = ((Client.Service.AisgPort)(this)).Test(inValue);
            return retVal.TestResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Service.TestResponse> Client.Service.AisgPort.TestAsync(Client.Service.Test request) {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Service.TestResponse> TestAsync(Client.Service.BaseRequestType TestRequest) {
            Client.Service.Test inValue = new Client.Service.Test();
            inValue.TestRequest = TestRequest;
            return ((Client.Service.AisgPort)(this)).TestAsync(inValue);
        }
    }
}
